### ISSUE TITLE
NullReferenceException - LookupClient.ProcessResponseMessage

### ISSUE THREAD

**Issue by Silvenga** [MichaCo/DnsClient.NET#136]
I haven't been able to reproduce this on demand, it only occurs under heavy load.

 ```
DnsClient.DnsResponseException: Query 43835 => pull-cmaf-f5.tiktokcdn.com IN A on 10.43.37.252:53 failed with an error.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DnsClient.LookupClient.ProcessResponseMessage(LookupClientAudit audit, DnsRequestMessage request, DnsResponseMessage response, DnsQuerySettings settings, NameServer nameServer, DnsMessageHandleType handleType, Int32 serverCount, Boolean isLastServer, HandleError& handleError)
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   at DnsClient.LookupClient.QueryInternalAsync(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers, CancellationToken cancellationToken)
 ```

The `DnsResponseException` had:
```
Code: Unassigned
DnsError: 'Unknown Error'
```

`10.43.37.252:53` is an unbound server acting in recursive mode with rate-limiting disabled.

**Comment by MichaCo** [comment]
The occurrence of a NullReferenceException should be fixed in 1.6. Not 100% sure though so let me know if that still happens
