### ISSUE TITLE
Cant read that many bytes error

### ISSUE THREAD

**Issue by ChrisEelmaa** [MichaCo/DnsClient.NET#22]
I am trying to query the hotmail.com servers like so:

```
var result = await this.lookupClient.QueryAsync("hotmail.com", QueryType.ANY).ConfigureAwait(false);
                var records = result.Answers.Where(record => record.RecordType == DnsClient.Protocol.ResourceRecordType.A ||
                                                             record.RecordType == DnsClient.Protocol.ResourceRecordType.AAAA ||
                                                             record.RecordType == DnsClient.Protocol.ResourceRecordType.MX);
```

however it blows up with the following response: 

```
DnsClient.DnsResponseException: Unhandled exception ---> System.IndexOutOfRangeException: Cannot read that many bytes: '68'.
   at DnsClient.DnsDatagramReader.ReadBytes(Int32 length)
   at DnsClient.DnsRecordFactory.ResolveTXTRecord(ResourceRecordInfo info)
   at DnsClient.DnsRecordFactory.GetRecord(ResourceRecordInfo info)
   at DnsClient.DnsMessageHandler.GetResponseMessage(ArraySegment`1 responseData)
   at DnsClient.DnsUdpMessageHandler.<QueryAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskExtensions.<WithCancellation>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DnsClient.LookupClient.<ResolveQueryAsync>d__63.MoveNext()
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.<ResolveQueryAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DnsClient.LookupClient.<QueryAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

I tried gmail.com instead, and it worked without problems. Any ideas?

**Comment by MichaCo** [comment]
That usually is caused by an invalid/incomplete message. The parser tries to read a message of a certain length but there is not enough data to read that from.

What DNS server are you using?

**Comment by ChrisEelmaa** [comment]
I'll do some more investigation later, however I don't think it's related to library itself.

```
Chriss-MBP:dotnet chriseelmaa$ host -a hotmail.com
Trying "hotmail.com"
Trying "hotmail.com"
;; Connection to 192.168.1.1#53(192.168.1.1) for hotmail.com failed: connection refused.
Chriss-MBP:dotnet chriseelmaa$ host -a google.com
Trying "google.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3608
;; flags: qr rd ra; QUERY: 1, ANSWER: 16, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.			IN	ANY

;; ANSWER SECTION:
google.com.		209	IN	A	216.58.213.110
google.com.		600	IN	MX	30 alt2.aspmx.l.google.com.
google.com.		600	IN	MX	10 aspmx.l.google.com.
google.com.		600	IN	MX	40 alt3.aspmx.l.google.com.
google.com.		600	IN	MX	50 alt4.aspmx.l.google.com.
google.com.		600	IN	MX	20 alt1.aspmx.l.google.com.
google.com.		345600	IN	NS	ns4.google.com.
google.com.		345600	IN	NS	ns3.google.com.
google.com.		345600	IN	NS	ns2.google.com.
google.com.		345600	IN	NS	ns1.google.com.

Received 503 bytes from 192.168.1.1#53 in 25 ms
Chriss-MBP:dotnet chriseelmaa$ nslookup hotmail.com
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	hotmail.com
Address: 204.79.197.212

```

**Comment by MichaCo** [comment]
If I run it with the library, e.g. on dnsclient.michaco.net, it totally works.
But those things depend on the response and that's DNS server dependent of course, so it is hard to reproduce for me if that's an internal DNS server you are using.
